# Generated by Django 4.2.7 on 2025-09-24 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered. Up to 11 digits allowed.', regex='^\\+?1?\\d{0,11}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered. Up to 11 digits allowed.', regex='^\\+?1?\\d{0,11}$')]),
        ),
    ]
