# Generated by Django 4.2.7 on 2025-09-16 21:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=200)),
                ('departure_location', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('days_of_operation', models.JSONField(default=list, help_text="List of days: ['monday', 'tuesday', ...]")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='users.transportorganizer')),
            ],
            options={
                'verbose_name': 'Transport Option',
                'verbose_name_plural': 'Transport Options',
                'db_table': 'transport_options',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TripUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('delay', 'Delay'), ('cancellation', 'Cancellation'), ('route_change', 'Route Change'), ('location', 'Location Update'), ('general', 'General Update')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('location_data', models.JSONField(blank=True, help_text="GPS coordinates: {'lat': 6.5244, 'lng': 3.3792}", null=True)),
                ('estimated_arrival', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_updates', to='users.transportorganizer')),
                ('transport_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_updates', to='transport.transportoption')),
            ],
            options={
                'verbose_name': 'Trip Update',
                'verbose_name_plural': 'Trip Updates',
                'db_table': 'trip_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.UUIDField(help_text='ID of the booking this review is for')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('transport_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='transport.transportoption')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('booking_id', 'student', 'transport_option')},
            },
        ),
    ]
